version: '3'

services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
    volumes:
      - "$HOME/docker/keycloak/providers:/opt/jboss/keycloak/providers"
      - "$HOME/docker/keycloak/themes:/opt/jboss/keycloak/themes"
      - "$HOME/docker/keycloak/standalone/data:/opt/jboss/keycloak/standalone/data"
      - "$HOME/docker/keycloak/standalone/log:/opt/jboss/keycloak/standalone/log"
    networks:
      - keycloak_infrastructure
    environment:
      - "APPLICATION_KAFKA_BROKERS_HOST=kafka"
      - "APPLICATION_KAFKA_TOPIC_NAME=registration-events"

networks:
  keycloak_infrastructure:
    external: true
